name: Format code
on: [push, pull_request]

jobs:
  run:
    name: Format code
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Prettier
        run: npm run fmt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format code using Prettier"
          # github.head_ref (string): head_ref or source branch of the pull request in a workflow run. 
          # (This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.)
          branch: ${{ github.head_ref }}
